services:
  web-mobile-ui:
    build:
      dockerfile: Dockerfile.web-mobile-ui
    container_name: Web-Mobile-UI-Dev
    command: npm run dev
    volumes:
      - ./web-mobile-ui/:/app
      - "${MEDIA_DATA_DIR}:/app/data"
      - Web-Mobile-UI-node-modules:/app/node_modules
    ports:
      - "${WEB_MOBILE_UI_PORT_DEV}:${WEB_MOBILE_UI_PORT_DEV}"
    networks:
      public:
        ipv4_address: "${WEB_MOBILE_UI_IPv4_DEV}"
    environment:
      VITE_BACK_END_LOCAL_IPv4: "${STREAM_API_HOST_IPv4_DEV}"
      VITE_BACK_END_PORT: "${STREAM_API_PORT_DEV}"
      VITE_PHOTO_DATA_DIR: "${PHOTO_DATA_DIR_WEB_MOBILE_UI_DEV}"
      VITE_VIDEO_DATA_DIR: "${VIDEO_DATA_DIR_WEB_MOBILE_UI_DEV}"
      VITE_SHORT_DATA_DIR: "${SHORT_DATA_DIR_WEB_MOBILE_UI_DEV}"


  stream-api:
    build:
      dockerfile: Dockerfile.stream-api
    container_name: Stream-API-Dev
    command: npm start
    volumes:
      - ./stream-api/:/app
      - "${MEDIA_DATA_DIR}:/app/data"
      - Stream-API-node-modules:/app/node_modules
    environment:
      PORT: "${STREAM_API_PORT_DEV}"
      PHOTO_DATA_DIR: "${PHOTO_DATA_DIR_STREAM_API}"
      VIDEO_DATA_DIR: "${VIDEO_DATA_DIR_STREAM_API}"
      SHORT_DATA_DIR: "${SHORT_DATA_DIR_STREAM_API}"
    ports:
      - "${STREAM_API_PORT_DEV}:${STREAM_API_PORT_DEV}"
    networks:
      public:
        ipv4_address: "${STREAM_API_IPv4_DEV}"

  face-api:
    build: 
      dockerfile: Dockerfile.face-api
    container_name: Face-API-Dev
    volumes:
      - "${MEDIA_DATA_DIR}:/app/data"
      - "./face-api/:/app"
    command: tail -f /dev/null 
    environment:
      POSTGRES_PASSWORD: "${PHOTO_DB_PASSWORD_DEV}"
      POSTGRES_USER: "${PHOTO_DB_USER_DEV}"
      DB_IP: "${PHOTO_DB_IPv4_DEV}"
      DB_PORT: "${PHOTO_DB_PORT_DEV}"
    networks:
      private:
        ipv4_address: "${FACE_API_IPv4_DEV}"
  
  photo-db:
    image: pgvector/pgvector:pg16
    container_name: Photo-DB-Dev
    volumes:
      - Photo-DB-pgdata:/var/lib/postgresql/data
      - "./photo-db/:/docker-entrypoint-initdb.d"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "${PHOTO_DB_PASSWORD_DEV}"
      POSTGRES_USER: "${PHOTO_DB_USER_DEV}"
    ports:
     - "${PHOTO_DB_PORT_DEV}:${PHOTO_DB_PORT_DEV}"
    networks:
      private:
        ipv4_address: "${PHOTO_DB_IPv4_DEV}"

volumes:
  Web-Mobile-UI-node-modules:
  Stream-API-node-modules:
  Photo-DB-pgdata:


networks:
  private:
    name: Private-Photo-App-Dev
    driver: bridge
    ipam:
      config:
       - subnet: "${PRIVATE_SUBNET_DEV}"
         gateway: "${PRIVATE_GATEWAY_DEV}"
  public:
    name: Public-Photo-App-Dev
    driver: bridge
    ipam:
      config:
        - subnet: "${PUBLIC_SUBNET_DEV}"
          gateway: "${PUBLIC_GATEWAY_DEV}"