services:
  build-web-mobile-ui:
    build:
      dockerfile: Dockerfile.web-mobile-ui
    container_name: Build-Web-Mobile-UI-Production
    volumes:
      - ./web-mobile-ui/:/app
      - Build-Web-Mobile-UI-node-modules:/app/node_modules
      - "Web-Mobile-UI-dist:/app/dist/"
    environment:
      VITE_BACK_END_LOCAL_IPv4: "${HOST_IPv4}"
      VITE_BACK_END_PORT: "${STREAM_API_PORT_PROD}"
      VITE_PHOTO_DATA_DIR: "${PHOTO_DATA_DIR_WEB_MOBILE_UI_PROD}"
      VITE_VIDEO_DATA_DIR: "${VIDEO_DATA_DIR_WEB_MOBILE_UI_PROD}"
      VITE_SHORT_DATA_DIR: "${SHORT_DATA_DIR_WEB_MOBILE_UI_PROD}"
    command: npm run build
    networks:
      Private:

  stream-api:
    build: 
      dockerfile: Dockerfile.stream-api
    container_name: Stream-API-Production
    volumes:
      - ./stream-api/:/app
      - "${MEDIA_DATA_DIR}:/media"
      - Stream-API-node-modules:/app/node_modules
    ports:
      - "${STREAM_API_PORT_PROD}:${STREAM_API_PORT_PROD}"
    environment:
      PORT: "${STREAM_API_PORT_PROD}"
      PHOTO_DATA_DIR: "${PHOTO_DATA_DIR_STREAM_API}"
      SHORT_DATA_DIR: "${SHORT_DATA_DIR_STREAM_API}"
      VIDEO_DATA_DIR: "${VIDEO_DATA_DIR_STREAM_API}"
    networks:
      Public:
    command: npm start

  web-mobile-ui:
    image: nginx
    container_name: Web-Mobile-UI-Production
    volumes:
      - "${MEDIA_DATA_DIR}:/usr/share/nginx/html/media"
      - "Web-Mobile-UI-dist:/usr/share/nginx/html"
    ports:
      - "${WEB_MOBILE_UI_PROD}:80"
    networks:
      Public:
    depends_on:
      build-web-mobile-ui:
        condition: service_completed_successfully

volumes:
  Build-Web-Mobile-UI-node-modules:
  Stream-API-node-modules:
  Web-Mobile-UI-dist:


networks:
  Private:
    driver: none
  Public:
    driver: bridge
