services:
  build-web-mobile-ui:
    build:
      dockerfile: Dockerfile.web-mobile-ui
    container_name: Build-Web-Mobile-UI-Production
    volumes:
      - ./web-mobile-ui/:/app
      - "${MEDIA_DATA_DIR}:/app/data"
      - Build-Web-Mobile-UI-node-modules:/app/node_modules
      - "Web-Mobile-UI-dist:/app/dist/"
    environment:
      VITE_BACK_END_LOCAL_IPv4: "${PROD_BACK_END_LOCAL_IPv4}"
      VITE_BACK_END_PORT: "${PROD_BACK_END_PORT}"
      VITE_PHOTO_DATA_DIR: "${PROD_PHOTO_DATA_DIR}"
      VITE_VIDEO_DATA_DIR: "${PROD_VIDEO_DATA_DIR}"
      VITE_SHORT_DATA_DIR: "${PROD_SHORT_DATA_DIR}"
    command: npm run build
    networks:
      Private:

  stream-api:
    build: 
      dockerfile: Dockerfile.stream-api
    container_name: Stream-API-Production
    volumes:
      - ./stream-api/:/app
      - "${MEDIA_DATA_DIR}:/app/data"
      - Stream-API-node-modules:/app/node_modules
    ports:
      - "${PROD_BACK_END_PORT}:${PROD_BACK_END_PORT}"
    environment:
      PORT: "${PROD_BACK_END_PORT}"
      PHOTO_DATA_DIR: "${DEV_PHOTO_DATA_DIR}"
      SHORT_DATA_DIR: "${DEV_SHORT_DATA_DIR}"
      VIDEO_DATA_DIR: "${DEV_VIDEO_DATA_DIR}"
    networks:
      Public:
    command: npm start

  web-mobile-ui:
    image: nginx
    container_name: Web-Mobile-UI-Production
    volumes:
      - "${MEDIA_DATA_DIR}:/usr/share/nginx/html/media"
      - "Web-Mobile-UI-dist:/usr/share/nginx/html"
    ports:
      - "${PROD_FRONT_END_PORT}:${PROD_FRONT_END_PORT}"
    networks:
      Public:
    depends_on:
      Build-Web-Mobile-UI:
        condition: service_completed_successfully

volumes:
  Build-Web-Mobile-UI-node-modules:
  Stream-API-node-modules:
  Web-Mobile-UI-dist:


networks:
  Private:
    name: Private-Photo-App-Production
    driver: bridge
    ipam:
  Public:
    name: Public-Photo-App-Production
    driver: bridge
    ipam:
