services:
  front-end:
    build:
      dockerfile: Dockerfile.front-end
    container_name: photo-app-front-end
    volumes:
      - ./front-end/:/app
      - "${MEDIA_DATA_DIR}:/app/data"
      - front-end-node-modules:/app/node_modules
    ports:
      - "${DEV_FRONT_END_PORT}:${DEV_FRONT_END_PORT}"
    networks:
      front-end:
    environment:
      - "VITE_BACK_END_LOCAL_IPv4=${DEV_BACK_END_LOCAL_IPv4}"
      - "VITE_BACK_END_PORT=${DEV_BACK_END_PORT}"
      - "VITE_PHOTO_DATA_DIR=${DEV_PHOTO_DATA_DIR}"
      - "VITE_VIDEO_DATA_DIR=${DEV_VIDEO_DATA_DIR}"
      - "VITE_SHORT_DATA_DIR=${DEV_SHORT_DATA_DIR}"
    command: npm run dev


  back-end:
    build:
      dockerfile: Dockerfile.back-end
    container_name: photo-app-back-end
    volumes:
      - ./back-end/:/app
      - "${MEDIA_DATA_DIR}:/app/data"
      - back-end-node-modules:/app/node_modules
    ports:
      - "${DEV_BACK_END_PORT}:${DEV_BACK_END_PORT}"
    networks:
      back-end:
    environment:
      - "PORT=${DEV_BACK_END_PORT}"
      - "PHOTO_DATA_DIR=${DEV_PHOTO_DATA_DIR}"
      - "VIDEO_DATA_DIR=${DEV_VIDEO_DATA_DIR}"
      - "SHORT_DATA_DIR=${DEV_SHORT_DATA_DIR}"
    command: npm start

volumes:
  front-end-node-modules:
  back-end-node-modules:


networks:
  back-end:
    name: photo-app-back-end
    ipam:
      driver: default
  front-end:
    name: photo-app-front-end
    ipam:
      driver: default
