services:
  web-mobile-ui:
    build:
      dockerfile: Dockerfile.web-mobile-ui
    container_name: Web-Mobile-UI-Dev
    command: npm run dev
    volumes:
      - ./web-mobile-ui/:/app
      - "${MEDIA_DATA_DIR}:/app/data"
      - Web-Mobile-UI-node-modules:/app/node_modules
    ports:
      - "${DEV_FRONT_END_PORT}:${DEV_FRONT_END_PORT}"
    networks:
      public:
        ipv4_address: "${DEV_FRONT_END_IPv4}"
    environment:
      VITE_BACK_END_LOCAL_IPv4: "${DEV_BACK_END_LOCAL_IPv4}"
      VITE_BACK_END_PORT: "${DEV_BACK_END_PORT}"
      VITE_PHOTO_DATA_DIR: "${DEV_PHOTO_DATA_DIR}"
      VITE_VIDEO_DATA_DIR: "${DEV_VIDEO_DATA_DIR}"
      VITE_SHORT_DATA_DIR: "${DEV_SHORT_DATA_DIR}"


  stream-api:
    build:
      dockerfile: Dockerfile.stream-api
    container_name: Stream-API-Dev
    command: npm start
    volumes:
      - ./stream-api/:/app
      - "${MEDIA_DATA_DIR}:/app/data"
      - Stream-API-node-modules:/app/node_modules
    environment:
      PORT: "${DEV_BACK_END_PORT}"
      PHOTO_DATA_DIR: "${DEV_PHOTO_DATA_DIR}"
      VIDEO_DATA_DIR: "${DEV_VIDEO_DATA_DIR}"
      SHORT_DATA_DIR: "${DEV_SHORT_DATA_DIR}"
    ports:
      - "${DEV_BACK_END_PORT}:${DEV_BACK_END_PORT}"
    networks:
      public:
        ipv4_address: "${DEV_BACK_END_IPv4}"

  face-api:
    build: 
      dockerfile: Dockerfile.face-api
    container_name: Face-API-Dev
    volumes:
      - "${MEDIA_DATA_DIR}:/app/data"
      - "./face-api/:/app"
    command: tail -f /dev/null 
    environment:
      POSTGRES_PASSWORD: "${DEV_DB_PASSWORD}"
      POSTGRES_USER: "${DEV_DB_USER}"
      DB_IP: "${DEV_DB_IPv4}"
      DB_PORT: "${DEV_DB_PORT}"
    networks:
      private:
        ipv4_address: "${DEV_FACE_API_IPv4}"
  
  photo-db:
    image: pgvector/pgvector:pg16
    container_name: Photo-DB-Dev
    volumes:
      - Photo-DB-pgdata:/var/lib/postgresql/data
      - "./photo-db/:/docker-entrypoint-initdb.d"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "${DEV_DB_PASSWORD}"
      POSTGRES_USER: "${DEV_DB_USER}"
    ports:
     - "${DEV_DB_PORT}:${DEV_DB_PORT}"
    networks:
      private:
        ipv4_address: "${DEV_DB_IPv4}"

volumes:
  Web-Mobile-UI-node-modules:
  Stream-API-node-modules:
  Photo-DB-pgdata:


networks:
  private:
    name: Private-Photo-App-Dev
    driver: bridge
    ipam:
      config:
       - subnet: "${DEV_PRIVATE_NETWORK}"
         gateway: "${DEV_PRIVATE_GATEWAY}"
  public:
    name: Public-Photo-App-Dev
    driver: bridge
    ipam:
      config:
        - subnet: "${DEV_PUBLIC_NETWORK}"
          gateway: "${DEV_PUBLIC_GATEWAY}"